### ISSUE TITLE
Error on cygwin

### ISSUE THREAD

**Issue by zemadmat** [maldevel/EmailHarvester#1]
Hello i'm trying to use emailHarvester on cygwin on windows 10
I have clone the repository then install using pip all was fine.

however when i try to execute it i have an error:
$ ./EmailHarvester.py -d example.com -e google
Traceback (most recent call last):
  File "./EmailHarvester.py", line 39, in <module>
    import requests
ImportError: No module named 'requests'

Have you any advice ?

**Comment by maldevel** [comment]
the project is working under python 3 and cygwin is using python 2 by default so be sure to install and use python 3 when you are running the script and let me know..

**Comment by maldevel** [comment]
I tried it and it is working. 
If you have already installed python3 on your win os do the following:
/cygdrive/c/Python35-32/Scripts/pip.exe install requests
/cygdrive/c/Python35-32/python.exe EmailHarvester.py -d example.com -e google

**Comment by n0xi** [comment]
Hi,

I have the same problem on OS X El Capitan 10.11.4  :/

`MacBook:EmailHarvester pierre$ ./EmailHarvester.py 
Traceback (most recent call last):
  File "./EmailHarvester.py", line 39, in <module>
    import requests
ImportError: No module named 'requests'`

`MacBook:EmailHarvester pierre$ pip install requests
Requirement already satisfied (use --upgrade to upgrade): requests in /Users/pierre/Library/Python/2.7/lib/python/site-packages
MacBook:EmailHarvester pierre$ pip install --upgrade requests
Requirement already up-to-date: requests in /Users/pierre/Library/Python/2.7/lib/python/site-packages`

how can i fix it ?

**Comment by zemadmat** [comment]
Many thanks, i have pip2 and not pip3. once all installed using pip3 it works fine.

**Comment by maldevel** [comment]
np mate. I am glad that it is working.
