### ISSUE TITLE
Search on google doesn't work

### ISSUE THREAD

**Issue by biva** [maldevel/EmailHarvester#13]
Great program!
But since the last release (1.3.0), searching on Google gives 0 result, while it gave results before.

For example: `./EmailHarvester.py -d microsoft.com -e google`
Gives: `No emails found!`

**Comment by maldevel** [comment]
Please check if your repository is up to date and you have the latest source code because it is working for me.

**Comment by biva** [comment]
Thank you for your answer. I did:
`git fetch origin`
`git fetch --tags`
`git checkout 1.3.0`

And now it works. I thought it was what I did yesterday, no idea why I had this result.

Thank you again!
