### ISSUE TITLE
Error on MAC OS X EL Capitan 10.11.4

### ISSUE THREAD

**Issue by n0xi** [maldevel/EmailHarvester#2]
Hi,

I have the same problem on OS X El Capitan 10.11.4  :/

`MacBook:EmailHarvester pierre$ ./EmailHarvester.py 
Traceback (most recent call last):
  File "./EmailHarvester.py", line 39, in <module>
    import requests
ImportError: No module named 'requests'`

`MacBook:EmailHarvester pierre$ pip install requests
Requirement already satisfied (use --upgrade to upgrade): requests in /Users/pierre/Library/Python/2.7/lib/python/site-packages
MacBook:EmailHarvester pierre$ pip install --upgrade requests
Requirement already up-to-date: requests in /Users/pierre/Library/Python/2.7/lib/python/site-packages`

how can i fix it ?

**Comment by maldevel** [comment]
hello, project is using python 3. Install/use python 3 and pip install requests package for python 3.

**Comment by n0xi** [comment]
ok, but my computer run Python 2.7.11 how can i run Python 3.x ?

**Comment by maldevel** [comment]
np ;) glad to see that it is working..
