### ISSUE TITLE
Combination of plugins/search-engines?

### ISSUE THREAD

**Issue by liar666** [maldevel/EmailHarvester#20]
Hi,

I've noticed that in the new version of EmailHarvester, combination of search-engines are used, like:
[+] Searching in Exalead + Linkedin: 100 results

I'm sorry I'm no Python expert, so reading the source code did not help me understand what it actually does?
Also, how does such combination improve the results?
Finally, could there be a way to control if such combinations should be used or not?

**Comment by lucgiffon** [comment]
Actually, Linkedin is not a search engine (it is a social network), but Exalead is. The combination Linkedin + Exalead means that the search engine "Exalead" is used with a specific search in site "Linkedin".

Take a look at this example:

https://www.exalead.com/search/web/results/?q=site%3Alinkedin.com

using the syntax "site:linkedin.com", you can notice that all the results are found in the site "linkedin.com"
