### ISSUE TITLE
TypeError: decode() argument 1 must be str, not None

### ISSUE THREAD

**Issue by liar666** [maldevel/EmailHarvester#22]
Hi,

I've modified the code as stated in #21 , but I don't think this changes anything about this error (appart the line numbers)...

$ ./EmailHarvester.py -e ask,bing,baidu,dogpile,yahoo -d alphagalileo.org
[+] User-Agent in use: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:40.0) Gecko/20100101 Firefox/40.1
[+] Using engine list: bing, yahoo, dogpile, ask, baidu
[+] Searching in Bing: 50 results
[+] Searching in Bing: 100 results
[+] Searching in Yahoo: 101 results
Traceback (most recent call last):
  File "EmailHarvester.py", line 277, in <module>
    all_emails += plugins[search_engine]['search'](domain, limit)
  File "plugins/dogpile.py", line 31, in search
    app_emailharvester.process()
  File "EmailHarvester.py", line 145, in process
    self.do_search()
  File "EmailHarvester.py", line 140, in do_search
    self.results = r.content.decode(r.encoding)
TypeError: decode() argument 1 must be str, not None

I'm a newbie in Python, so I'm not sure which part of the following line is "None" (r? r.content? or r.encoding?), nor why it is and should not be...
    self.results = r.content.decode(r.encoding)

**Comment by lucgiffon** [comment]
You can test which part is None with something like:

```
if smth is None:
    print("Smth is none")
```

I'm not sure but i think is is r.encoding which is None because:
if r or r.content was None, the error should be AttributeError: NoneType has no attribute content / decode
