### ISSUE TITLE
Fails to import Python dependencies 

### ISSUE THREAD

**Issue by Shakyamuni177te** [maldevel/EmailHarvester#25]
Tested on Fedora 24 and Kali Linux. Both systems I'm getting an error:

    ImportError: No module named 'requests'

On the Fedora 24 system and:

    ImportError: No module named 'validators'

On the Kali machine.

Running `pip install requests`/`pip install validators` does not resolve and results in messages stating that the package is already installed.

**Comment by Shakyamuni177te** [comment]
I found a different program to use instead.

**Comment by its0x08** [comment]
thats shit actually... happened to me also.
i just commented the line that import validators in the code and its working a bit better than before. LOL

**Comment by its0x08** [comment]
never mind about comenting it bcz it does not fix anything at all...
this is the library u need man @Shakyamuni177te ..
https://github.com/kvesteri/validators
download and install it!
