### ISSUE TITLE
ImportError: No module named 'requests'

### ISSUE THREAD

**Issue by aceoner187** [maldevel/EmailHarvester#4]
Hello,

I'm having this problem when i'm using the script:

File "./EmailHarvester.py", line 39, in <module>
import requests
ImportError: No module named 'requests'

**Comment by maldevel** [comment]
hello, you have to install this module. please read readme file.

**Comment by Roslekas** [comment]
1. manualy need to create folder /root/.local/lib/python3.4/site-packages
2. copy site-packages from /root/.local/lib/python2.7/site-packages to /usr/local/lib/python3.4
3. pip install --upgrade --target=/root/.local/lib/python3.4/site-packages colorama
4. pip install --upgrade --target=/root/.local/lib/python3.4/site-packages tempcolor
5. pip install --upgrade --target=/root/.local/lib/python3.4/site-packages requests
for me helped
